# Generated by Django 3.1.7 on 2021-10-28 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_auto_20211017_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='company_size',
            field=models.CharField(blank=True, choices=[('size_1-9', '1-9'), ('size_10-49', '10-49'), ('size_50-99', '50-99'), ('size_100', '100+')], default='size_1-9', max_length=20, null=True),
        ),
    ]
