# Generated by Django 3.1.7 on 2021-11-20 22:47

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0003_userprofile_skill_set'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='skill_set',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Python', 'Python'), ('AWS', 'AWS'), ('Azure', 'Azure')], max_length=16),
        ),
    ]
