# Generated by Django 3.1.7 on 2021-12-01 03:47

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0004_auto_20211120_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='skill_set',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Python', 'Python'), ('AWS', 'AWS'), ('Azure', 'Azure'), ('None', 'None')], default='none', max_length=21),
        ),
    ]
